### PR TITLE
New release supporting 2018, new names, etc.

### PR DESCRIPTION
**Pull request by jamesmunns**
This is my current WIP. This is not ready to merge.

All PRs in this family:

* [nrf52832-pac]
* [nrf52840-pac]
* [nrf52-hal]

[nrf52832-pac]: https://github.com/nrf-rs/nrf52832-pac/pull/11
[nrf52840-pac]: https://github.com/nrf-rs/nrf52840-pac/pull/2
[nrf52-hal]: https://github.com/nrf-rs/nrf52-hal/pull/32

### CODE REVIEW

**Comment by jamesmunns** [comment]
Note: I have used master of svd2rust to regenerate this code. As v0.14 is dropping soon, I expect to use that if it is ready in time.

I have also removed the nrf52840 items, as they have been moved to their own repo.

**Comment by wez** [comment]
re: svd2rust; https://github.com/nrf-rs/nrf52832-pac/issues/3 is our issue tracking why we were not using mainstream.  I'm pretty disappointed that things haven't moved over there in many months.

**Comment by jamesmunns** [comment]
Hey @nrf-rs/nrf52, I believe this is ready to land now. I have already cut a release and published on crates.io as `0.6.0-beta.1`. Could you please test with your crates locally, and let me know how it goes?

I'd like to merge this sooner than later, and if we need to iterate on `master` before we cut the final `0.6.0` release, that works for me.

Please see the related issues linked above for this family of PRs.

**Review by hannobraun — COMMENTED** [review]
I don't have time right now to review the changes from the svd2rust update, but the rest looks good to me.

I'm concerned though about moving from @wez's svd2rust fork back to mainline (see https://github.com/nrf-rs/nrf52832-pac/issues/3). You addressed part of the problem in the SVD file itself, but what about the handling of `derivedFrom`? Is that relevant in this crate?

**Comment by jamesmunns** [comment]
@hannobraun you're right, my move back to mainline was premature.

I have opened https://github.com/rust-embedded/svd2rust/pull/256, which even if it isn't merged, could likely be used for now, as it combines the work of @wez's PR with the newest bits of svd2rust. This is additionally blocked by https://github.com/japaric/svd/issues/62 - which would prevent my PR from being mergeable (currently has a git dependency on the HEAD of the `svd` crate).

**Comment by jamesmunns** [comment]
Hey @wez, I'm a little confused. I regenerated the crate with my branch that incorporates your changes, but nothing really changed, other than the 0.14 stuff.

Are the things that are `derivedFrom` showing up properly? Was my merge in https://github.com/rust-embedded/svd2rust/pull/256 correct?

Could you check this, and see if it still has the problems seen in #3? If necessary, you can probably use `form` 0.3.0, the switch to 0.4.0 is what caused so much noise in this PR.

**Comment by jamesmunns** [comment]
Actually, I think #3 is no longer necessary. You can see that ~~SPIM3~~ SPIM2, which is a derived register, is available here in the `beta.1`release, which does **NOT** have the changes from https://github.com/rust-embedded/svd2rust/pull/256.

Docs: https://docs.rs/nrf52832-pac/0.6.0-beta.1/nrf52832_pac/struct.SPIM2.html (note that the RegisterBlock correctly points to the `SPIM0` types.

Relevant SVD snippet:

```xml
    <peripheral derivedFrom="SPIM0">
      <name>SPIM2</name>
      <description>Serial Peripheral Interface Master with EasyDMA 2</description>
      <groupName>SPIM</groupName>
      <baseAddress>0x40023000</baseAddress>
      <size>32</size>
      <interrupt>
        <name>SPIM2_SPIS2_SPI2</name>
        <value>35</value>
      </interrupt>
    </peripheral>
```

Based on this, I'd like to move forward with this merge and release.

CC @hannobraun, @wez

**Comment by hannobraun** [comment]
@jamesmunns 
> Based on this, I'd like to move forward with this merge and release.

I'm mostly ignorant about the workings of SVD at this level of detail, and was just mentioning what I saw as a potential oversight. If you and @wez are happy, I'm happy too!

**Comment by jamesmunns** [comment]
Okay, final call! @wez and @hannobraun, I have made some final changes (using svd2rust 0.14.0 to generate this code, changed the version number).

I will plan on merging this in 24 hours, if I do not hear an objection from either of you :)

**Comment by jamesmunns** [comment]
Okay, I lied, I am going to run with it. We can drop a point release if there are any issues, I have some time tonight and would like this to be done done. Sorry for the noise.

**Comment by hannobraun** [comment]
In any case, I just looked over the new commits, no objections. You have my belated approval :)

**Pull request merged**
