### PR TITLE
Get project up to date

### PR DESCRIPTION
**Pull request by hannobraun**
This pull requests re-generates the code using the latest svd2rust and updates all dependencies. I've also added a script that automates and documents the update procedure.

### CODE REVIEW

**Comment by hannobraun** [comment]
@jamesmunns I realize I can merge this myself, but even though this seems fairly uncontroversial, I wanted to give you the chance to take a look.

**Comment by jamesmunns** [comment]
LGTM! Script is a great starting place. Do you want to rev the version number in this PR so we can publish this to crates?

Also add your self as a contributor in the Cargo.toml :)

**Comment by hannobraun** [comment]
Pushed two new commits that update the version number and add myself to `Cargo.toml`.

**Review by jamesmunns — COMMENTED** [review]
LGTM! I can push this to crates this weekend. I can then also add you as an approved publisher there as well.

**Review by jamesmunns — APPROVED** [review]

**Comment by hannobraun** [comment]
> I can then also add you as an approved publisher there as well.

Thanks, I'm happy to help out.

**Pull request merged**
